package hydrust:protocol@0.1.1;

interface types {
    record stream-info {
        title: string,
        video-url: string,
        audio-url: option<string>,
    }

    record browser-request {
        title: string,
        video-url: string,
        audio-url: option<string>,
    }

    record error-code {
        title: string,
        video-url: string,
        audio-url: option<string>,
    }
}

interface events {
    use types.{stream-info, browser-request, error-code};

    /// --- PLUGIN NAMESPACE ---
    /// Events sent by the WASM Extension to the Core
    variant plugin-event {
        /// "I can handle this URL"
        identified(string),
        /// "I need the browser to sniff a pattern"
        request-browser(browser-request),
        /// "I need the user to solve a captcha"
        request-captcha(string), 
        /// "Here is the final stream data"
        result-ready(stream-info),
        /// "Something went wrong in the logic"
        error(error-code),
    }

    /// --- CORE NAMESPACE ---
    /// Events sent by the Engine/Services to the Plugins
    variant core-event {
        /// "Does anyone support this URL?"
        intent-resolve(string),
        /// "The browser found the data you requested"
        browser-observed(string),
        /// "The captcha has been solved"
        captcha-solved(string),
    }

    /// --- SERVICE NAMESPACE ---
    /// Global signals about the internal engine state
    variant service-event {
        /// "Muxing progress update"
        media-progress(f32),
        /// "The file is finished and saved"
        media-complete(string),
    }

    /// The Unified Event Wrapper
    record event {
        id: string,         // Trace ID (UUID)
        origin: string,     // Name of the sender
        timestamp: u64,
        payload: event-payload,
    }

    variant event-payload {
        plugin(plugin-event),
        core(core-event),
        service(service-event),
    }
}

interface metadata {
    record plugin-info {
        name: string,
        version: string,
        author: string,
        description: string,
    }
}

world site-provider {
    import wasi:io/poll@0.2.8;
    import wasi:clocks/wall-clock@0.2.8;

    use metadata.{plugin-info};
    use events.{event};

    // Plugin must provide this information
    export get-info: func() -> plugin-info;

    import publish: func(ev: event);
    export on-event: func(ev: event);
}